config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: "home#index"
  resources :equipaments
  resources :places
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/equipament.rb
class Equipament < ApplicationRecord
  enum kind: [ :ar_condicionado, :cafeteira,
               :computador, :monitor, :mouse, :teclado, :televisao, :roteador ]

  validates :name, :kind, :brand, presence: true

  has_one_attached :picture

  belongs_to :place
  paginates_per 5

  scope :for_name, ->(name) { where(["name LIKE ?", "%#{name}%"]) }
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :equipaments
  belongs_to :parent, class_name: "Place", optional: true
  validates_presence_of :name
  paginates_per 5

  scope :for_name, ->(name) { where(["name LIKE ?", "%#{name}%"]) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/equipaments_controller.rb
class EquipamentsController < ApplicationController
  before_action :set_places, only: %i[create new edit update]
  before_action :set_equipament, only: %i[show edit destroy update]
  def index
    @equipaments = Equipament.page(params[:page])
    name_field = params[:name]
    if name_field.present?
      @equipaments = Equipament.for_name(name_field).page(params[:page])
    end
  end

  def new
    @equipament = Equipament.new
  end

  def create
    convert_kind
    @equipament = Equipament.new(equipament_params)
    if @equipament.save
      redirect_to equipaments_path, notice: 'equipament was successfully created!'
    else
      render :new
    end
  end

  def show; end
  def edit; end

  def update
    convert_kind
    if @equipament.update(equipament_params)
      redirect_to equipaments_path, notice: 'equipament was successfully updated!'
    else
      render :edit
    end
  end

  def destroy
      @equipament.destroy
      redirect_to equipaments_path, notice: 'equipament was successfully destroyed!'
  end

  private
  def convert_kind
    params[:equipament][:kind] = (params[:equipament][:kind]).to_i
  end
  def set_places
    @places = Place.all
  end
  def set_equipament
    @equipament = Equipament.find(params[:id])
  end

  def equipament_params
    params.require(:equipament).permit(:name, :brand, :kind, :picture, :place_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_places, only: %i[create new edit update]
  before_action :set_place, only: %i[show edit destroy update]
  def index
    @places = Place.page(params[:page])
    name_field = params[:name]
    if name_field.present?
      @places = Place.for_name(name_field).page(params[:page])
    end
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to places_path, notice: 'place was successfully created!'
    else
      render :new
    end
  end

  def show; end
  def edit; end

  def update
    if @place.update(place_params)
      redirect_to places_path, notice: 'place was successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @place.destroy
    redirect_to places_path, notice: 'place was successfully destroyed!'

  end

  private
  def set_places
    @places = Place.all
  end
  def set_place
    @place = Place.find(params[:id])
  end

  def place_params
    params.require(:place).permit(:name, :parent_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when "alert"
        "alert alert-warning alert-dismissible fade show"
      when  "notice"
        "alert alert-success alert-dismissible fade show"
      when "error"
        "alert alert-danger alert-dismissible fade show"
      else
        "alert alert-primary alert-dismissible fade show"
      end
  end
end

app/helpers/equipaments_helper.rb
module EquipamentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/equipaments/_form.html.erb
<%= form_with model: equipament do |form| %>
  <% if equipament.errors.any? %>
      <ul>
        <% equipament.errors.each do |error| %>
          <div class="<%= flash_class('error') %>" role="alert">
            <%= error.full_message %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
      </ul>
  <% end %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :brand %>
    <%= form.text_field :brand , class: "form-control" %>
  </div>
  <div class="form-group mt-2">
    <%= form.label :kind %>
    <%= form.select :kind , Equipament.kinds, class: "form-control" %>
  </div>
  <div class="form-group mt-2">
    <%= form.label :place_id %>
    <%= form.collection_select(:place_id, @places, :id, :name, include_blank: true, class: 'form-control' ) %>
  </div>
  <div class="form-group">
    <%= form.label :picture %>
    <%= form.file_field :picture , class: 'form-control' %>
  </div>

  <div class="mt-2">
    <%= form.submit t("send"), class: "btn btn-primary" %>
  </div>
<% end %>

<div class="pt-3">
  <%= link_to t('back'), equipaments_path %>
</div>

app/views/equipaments/edit.html.erb
<section class="py-5">
  <h1><%= t('edit') %> equipamento</h1>

  <%= render 'form', equipament: @equipament %>
</section>

app/views/equipaments/index.html.erb
<section class="py-3">
  <%= form_tag(equipaments_path, method: :get) do %>
  <div class="form-group mt-3 col-sm-10">
      <%= t('search-e') %>
      <%= text_field_tag(:name) %>
      <%= submit_tag(t"Search") %>
    <% end %>
  </div>
  
  <br>
  <table class="table">
    <th><%= t('id') %></th>
    <th><%= t('name') %></th>
    <th><%= t('kind') %></th>
    <th><%= t('brand') %></th>
    <th colspan="3"> <%= link_to 'Adicionar equipamento', new_equipament_path,   class: 'btn btn-primary btn-lg' %> </th>
  <% if @equipaments.count() > 0%>
    <% @equipaments.each do |equipament| %>
      <tr>
        <td><%= equipament.id %></td>
        <td><%= equipament.name %></td>
        <td><%= equipament.kind %></td>
        <td><%= equipament.brand %></td>
        <td > <%= link_to t('edit'), edit_equipament_path(equipament) ,
        class: 'btn btn-warning' %></td>
        <td > <%= link_to t('show'), equipament_path(equipament),
          class: 'btn btn-info'  %> </td>
        <td > <%= link_to t('delete'), equipament_path(equipament),
          method: :delete, data: { confirm: 'Você está certo disso ?' }, 
          class: 'btn btn-danger'%> </td>
      </tr>
    <% end %>
    <% else %>
      <tr class="text-align center">No equipaments yet.</tr>
    <% end %>
  </table>
  
    
  <div class="row">
    <div class="text-center">
      <%= paginate @equipaments %>
    </div>  
  </div>
</section>

app/views/equipaments/new.html.erb
<section class="py-5">
  <h1><%= t('new') %> equipamento</h1>

  <%= render 'form', equipament: @equipament %>
</section>

app/views/equipaments/show.html.erb
<div class="row d-flex justify-content-center mt-5 ">
  <div class="col-md-6">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= @equipament.name %></h5>
        <p class="card-text">Tipo: <%= @equipament.kind %></p>
        <p class="card-text">Marca: <%= @equipament.brand %></p>
      </div>
    </div>
    <div class="col-md-3 mt-5">
      <% if @equipament.picture.persisted? %>
        <%= image_tag @equipament.picture %>
      <% else %>
        <h3>No picture available </h3>
      <% end %>
    </div>
  </div>
  <div class="col-3-md">
    <%= link_to t('back'), equipaments_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/home/index.html.erb
<!-- inside app/views/home/index.html.erb -->
<h1>Welcome, this is the home page</h1>

<button type="button"
        class="btn btn-lg btn-danger"
        data-bs-toggle="popover"
        title="Popover title"
        data-bs-content="Amazing content, right ?">
  Click to toggle popover
</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class="container">
    <%= render "shared/navigation" %>

    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>" role="alert">
        <%= value %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_with model: place do |form| %>
  <% if place.errors.any? %>
    <ul>
      <% place.errors.each do |error| %>
        <div class="<%= flash_class('error') %>" role="alert">
          <%= error.full_message %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
    </ul>
  <% end %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group mt-2">
    <%= form.label :parent %>
    <%= form.collection_select(:parent_id, @places, :id, :name, include_blank: true, class: 'form-control' ) %>
  </div>

  <div class="mt-2">
    <%= form.submit t("send"), class: "btn btn-primary" %>
  </div>
<% end %>

<div class="pt-3">
  <%= link_to t('back'), places_path %>
</div>

app/views/places/edit.html.erb
<section class="py-5">
  <h1><%= t('edit') %> local</h1>

  <%= render 'form', place: @place %>
</section>

app/views/places/index.html.erb
<section class="py-3">
  <%= form_tag(places_path, method: :get) do %>
  <div class="form-group mt-3 col-sm-10">
      <%= t('search-l') %>
      <%= text_field_tag(:name) %>
      <%= submit_tag(t"Search") %>
    <% end %>
  </div>
  
  <br>
  <table class="table">
    <th><%= t('id') %></th>
    <th><%= t('name') %></th>
    <th><%= t('parent') %></th>
    <th colspan="3"> <%= link_to 'Adicionar local', new_place_path, class: 'btn btn-primary btn-lg' %> </th>
  <% if @places.count() > 0%>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.id %></td>
        <td><%= place.name %></td>
        <% if place.parent_id %>
        <td><%= place.parent.name %></td>
        <% else %>
          <td> Não há </td>
        <% end %>
        <td > <%= link_to t('edit'), edit_place_path(place) ,
        class: 'btn btn-warning' %></td>
        <td > <%= link_to t('show'), place_path(place),
          class: 'btn btn-info'  %> </td>
        <td > <%= link_to t('delete'), place_path(place),
          method: :delete, data: { confirm: 'Você está certo disso ?' }, 
          class: 'btn btn-danger'%> </td>
      </tr>
    <% end %>
    <% else %>
      <tr class="text-align center">No places yet.</tr>
    <% end %>
  </table>
  
    
  <div class="row">
    <div class="text-center">
      <%= paginate @places %>
    </div>  
  </div>
</section>

app/views/places/new.html.erb
<section class="py-5">
  <h1><%= t('new') %> local</h1>

  <%= render 'form', place: @place %>
</section>

app/views/places/show.html.erb
<div class="row d-flex justify-content-center mt-5 ">
  <div class="col-md-6">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= @place.name %></h5>
        <% if @place.parent %>
          <p class="card-text">local: <%= @place.parent.name %></p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-3-md">
    <%= link_to t('back'), places_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Gestão de Inventário</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item p-2">
                <%= link_to t('equipaments'), equipaments_path, class: "dropdown-item"  %>
              </li>
              <li class="nav-item p-2">
                <%= link_to t('places'), places_path, class: "dropdown-item"  %>
              </li>
            </ul>
        </div>
    </div>
</nav>